// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace BlazingPizza.Server.Models
{
    public partial class PizzaStoreContextModel
    {
        partial void Initialize()
        {
            var address = AddressEntityType.Create(this);
            var latLong = LatLongEntityType.Create(this);
            var notificationSubscription = NotificationSubscriptionEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var pizza = PizzaEntityType.Create(this);
            var pizzaSpecial = PizzaSpecialEntityType.Create(this);
            var pizzaTopping = PizzaToppingEntityType.Create(this);
            var pizzaStoreUser = PizzaStoreUserEntityType.Create(this);
            var topping = ToppingEntityType.Create(this);
            var deviceFlowCodes = DeviceFlowCodesEntityType.Create(this);
            var key = KeyEntityType.Create(this);
            var persistedGrant = PersistedGrantEntityType.Create(this);
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);

            LatLongEntityType.CreateForeignKey1(latLong, order);
            OrderEntityType.CreateForeignKey1(order, address);
            PizzaEntityType.CreateForeignKey1(pizza, order);
            PizzaEntityType.CreateForeignKey2(pizza, pizzaSpecial);
            PizzaToppingEntityType.CreateForeignKey1(pizzaTopping, pizza);
            PizzaToppingEntityType.CreateForeignKey2(pizzaTopping, topping);
            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, identityRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, pizzaStoreUser);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, pizzaStoreUser);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, identityRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, pizzaStoreUser);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, pizzaStoreUser);

            AddressEntityType.CreateAnnotations(address);
            LatLongEntityType.CreateAnnotations(latLong);
            NotificationSubscriptionEntityType.CreateAnnotations(notificationSubscription);
            OrderEntityType.CreateAnnotations(order);
            PizzaEntityType.CreateAnnotations(pizza);
            PizzaSpecialEntityType.CreateAnnotations(pizzaSpecial);
            PizzaToppingEntityType.CreateAnnotations(pizzaTopping);
            PizzaStoreUserEntityType.CreateAnnotations(pizzaStoreUser);
            ToppingEntityType.CreateAnnotations(topping);
            DeviceFlowCodesEntityType.CreateAnnotations(deviceFlowCodes);
            KeyEntityType.CreateAnnotations(key);
            PersistedGrantEntityType.CreateAnnotations(persistedGrant);
            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);

            AddAnnotation("ProductVersion", "7.0.0");
        }
    }
}
